name: user-service-api integration test
run-name: ${{ github.actor }} is testing out Github Actions 🚀

# workflow will be triggered whenever there are push or pull reques on develop branch
# you can add more branch by adding it on array
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is running on a ${{ runner.os }} server hosted by Github."
      - run: echo "The name of your branch is  ${{ github.ref }} and your repository is ${{ github.repository }}."
  build:
    runs-on: "ubuntu-latest"
    steps:
      # clone repository code to virtual machine on github
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node v.18 on github virtual machine
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Execute build
        run: npm run build
  test:
    runs-on: "ubuntu-latest"
    needs: build
    steps:
      # clone repository code to virtual machine on github
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node v.18 on github virtual machine
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Execute test
        run: npm run test
